### ISSUE TITLE
Error on wasm Go

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/wasm-bench#3]
```
Wasm (Go)
TypeError: Reflect.get called on non-object
    at Object.get (<anonymous>)
    at syscall/js.valueGet (/Users/hajimehoshi/go/src/github.com/hajimehoshi/wasm-bench/wasm_exec.js:198:35)
    at syscall_js.valueGet (wasm-function[1008]:7)
    at syscall_js.Value.Get (wasm-function[995]:124)
    at syscall_js.init (wasm-function[1006]:730)
    at syscall.init (wasm-function[1041]:470)
    at time.init (wasm-function[1064]:374)
    at main.init (wasm-function[1497]:222)
    at runtime.main (wasm-function[446]:1074)
    at _rt0_wasm_js (wasm-function[851]:71)
```

**Comment by patrickmn** [comment]
Would you mind sharing the solution?

**Comment by hajimehoshi** [comment]
Just use the latest `wasm_exec.js`.

**Comment by patrickmn** [comment]
That worked. Thank you!

**Comment by hajimehoshi** [comment]
Oh you found the same problem? I'm glad that you solved this :-)

**Comment by patrickmn** [comment]
Yeah, this was the only result on Google :)

**Comment by caffeinum** [comment]
@hajimehoshi @patrickmn 

Have the same problem, which `wasm_exec.js` do you use? I have tried both this repo's and one from official repo, still errores https://raw.githubusercontent.com/golang/go/master/misc/wasm/wasm_exec.js
https://github.com/hajimehoshi/wasm-bench/blob/master/f64/wasm_exec.js

EDIT: looks like my problem wasn't with the `wasm_exec.js` script, though nice error message would have helped. Please consider something around this:

```javascript
  // func valueGet(v ref, p string) ref
 "syscall/js.valueGet": (sp) => {
    console.log('obj', loadValue(sp + 8))
    console.log('key', loadString(sp + 16))

    try {
      const obj = Reflect.get(loadValue(sp + 8), loadString(sp + 16))
      storeValue(sp + 32, obj);
      console.log('value', obj)
     } catch (err) {
      console.error(err)
     }
  },
```

**Comment by hajimehoshi** [comment]
I've not touched this project recently. PRs are welcome!
